# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestworkqq():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testworkqq(self):
    # Test name: test_workqq
    # Step # | name | target | value | comment
    # 1 | open | https://work.weixin.qq.com/ |  | 
    self.driver.get("https://work.weixin.qq.com/")
    # 2 | setWindowSize | 1265x693 |  | 
    self.driver.set_window_size(1265, 693)
    # 3 | click | linkText=立即注册 |  | 
    self.driver.find_element(By.LINK_TEXT, "立即注册").click()
    # 4 | click | id=corp_name |  | 
    self.driver.find_element(By.ID, "corp_name").click()
    # 5 | type | id=corp_name | hogwwardds | 
    self.driver.find_element(By.ID, "corp_name").send_keys("hogwwardds")
    # 6 | click | id=register_tel |  | 
    self.driver.find_element(By.ID, "register_tel").click()
    # 7 | type | id=manager_name | xixi | 
    self.driver.find_element(By.ID, "manager_name").send_keys("xixi")
    # 8 | click | id=submit_btn |  | 
    self.driver.find_element(By.ID, "submit_btn").click()
  
