# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

def test(a,b,c):
  return a+b+c

d = (1,2,30)
print(test(*d))

#
# class TestTestbaidu(unittest.TestCase):
#   def setup_method(self, method):
#     self.driver = webdriver.Firefox("/Users/juanxu/Desktop/workspace/project/selenium_study/selenium_server/geckodriver")
#     self.vars = {}
#
#   def teardown_method(self, method):
#     self.driver.quit()
#
#   def test_testbaidu(self):
#     self.driver.get("https://www.baidu.com/")
#     self.driver.set_window_size(1265, 693)
#     self.driver.find_element(By.ID, "kw").send_keys("appium")
#     self.driver.find_element(By.ID, "su").click()
#
# if __name__ == '__main__':
#   unittest.main()